
@baseUrl = https://us-central1-elearning-910d5.cloudfunctions.net/api
### Example of endpoints for basic CRUD operations.
#    Later in your submission, leave only the one that you actually use and remove others from this file.


### Get the calendar event
GET {{baseUrl}}/calendar

###
GET {{baseUrl}}/quotes/7hafVnkozwXR6u2world

###
POST {{baseUrl}}/calendar
Content-Type: application/json

{
    "date": "23-07-2020",
    "description" : "Rest"
}

