# @baseUrl = https://us-central1-ex4-firebase.cloudfunctions.net/api
@baseUrl = http://192.168.0.157:3000
### Example of endpoints for basic CRUD operations.
#    Later in your submission, leave only the one that you actually use and remove others from this file.


### Get the list of quotes
GET {{baseUrl}}/students

###  Getting a quote for a given id
GET {{baseUrl}}/quotes/IM08kcYelARMk2PdUpab

###  Add a new quote
PATCH {{baseUrl}}/students
Content-Type: application/json

{
    "email": "t2112312y",
    "phone" : "asdwa"
}

### Update a quote partly
PATCH {{baseUrl}}/quotes/NKWy8rZpL1HWOB2Jnl3f
Content-Type: application/json

{
        "like" : 10
}

###
PATCH {{baseUrl}}/quotes/NKWy8rZpL1HWOB2Jnl3f
Content-Type: application/json

{
        "dislike" : 2
}

### Replace an existing quote entirely
PUT {{baseUrl}}/quotes/NKWy8rZpL1HWOB2Jnl3f
Content-Type: application/json

{
    "data": "Programming is not everything",
    "like" : 5,
    "dislike" : 5
}

### Delete a quote
DELETE {{baseUrl}}/quotes/NKWy8rZpL1HWOB2Jnl3f

### Thumb up (or Like) - Update the 'like' attribute by inreasing by 1
PATCH {{baseUrl}}/quotes/SYGBgxzLVguLbJqjJIUr/like

###
PATCH {{baseUrl}}/like/SYGBgxzLVguLbJqjJIUr

###
PATCH {{baseUrl}}/quotes/SYGBgxzLVguLbJqjJIUr?vote=like

